# build matrix consists of different versions of Sage on different platforms.
# the versions are obtained via tarball download since Sage is not a supported
# "language" in TravisCI
#
# choice of Sage version is determined via environment variables
#
env:
  global:
    - SAGE=${HOME}/SageMath/sage

matrix:
  include:
    - os: linux
      env:
        - SAGE_TARBALL=sage-8.0-Ubuntu_14.04-x86_64.tar.bz2
        - SAGE_SERVER=http://mirrors.mit.edu/sage/linux/64bit
      dist: trusty
    - os: osx
      env:
        - SAGE_TARBALL=sage-8.0-OSX_10.12.6-x86_64.tar.bz2
        - SAGE_SERVER=http://mirrors.mit.edu/sage/osx/intel
      osx_image: xcode9.1  # OSX 10.12


before_install:
  - cd ${HOME}

  # download Sage as a torrent 
  - |
    if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      HOMEBREW_NO_AUTO_UPDATE=1 brew install aria2
      wget http://www.mirrorservice.org/sites/www.sagemath.org/osx/intel/meta/${SAGE_TARBALL}.torrent
      aria2c ${SAGE_TARBALL}.torrent --file-allocation=falloc --seed-time=0
    fi

  # download sage directly
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then wget ${SAGE_SERVER}/${SAGE_TARBALL}; fi

  # extract Sage
  - travis_wait tar xjf ${HOME}/${SAGE_TARBALL}

  # OpenSSL is missing for Sage on OSX but is required to use pip securely
  # So download 'by hand' concurrencytest (used to run tests in parallel) and its dependencies
  - |
    if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      wget https://pypi.python.org/packages/ba/8a/8286de6d3aa9a3c4765cb3dd73515d91129f012a61e0ec8578c733ea2d27/concurrencytest-0.1.2.tar.gz#md5=773d9a8be83fc043a32a25b6665bf59b
      wget https://pypi.python.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl#md5=c37216a954c8669054e2b2c54853dd49
      wget https://pypi.python.org/packages/03/e9/e915af1f97914cd0bc021e125fd1bfd4106de614a275e4b6866dd9a209ac/extras-1.0.0-py2.py3-none-any.whl#md5=9a2a42996d242746bdad945d8b2617e5
      wget https://pypi.python.org/packages/a8/28/7eed6bf76792f418029a18d5b2ace87ce7562927cdd00f1cefe481cd148f/fixtures-3.0.0-py2.py3-none-any.whl#md5=f6e3afc70aba24d85d7f04e28771f760
      wget https://files.pythonhosted.org/packages/c7/a3/c5da2a44c85bfbb6eebcfc1dde24933f8704441b98fdde6528f4831757a6/linecache2-1.0.0-py2.py3-none-any.whl
      wget https://pypi.python.org/packages/0c/5d/b077dbf309993d52c1d71e6bf6fe443a8029ea215135ebbe0b1b10e7aefc/pbr-3.1.1-py2.py3-none-any.whl#md5=75a0f55856bfc9220af0d01244afec43
      wget https://pypi.python.org/packages/26/2e/03bce213a9bf02a2750dcb04e761785e9c763fc11071edc4b447eacbb842/python_mimeparse-1.6.0-py2.py3-none-any.whl#md5=e2780ceb12929f2f8557c467fa8c2567
      wget https://pypi.python.org/packages/75/00/f5829197ddfb9b8ff68b2995b5bb33519ec889282d45c27a7b98d2f40752/python_subunit-1.2.0-py2.py3-none-any.whl#md5=bb666fe045f8d3989e78c7cd90d6d394
      wget https://pypi.python.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl#md5=866ab722be6bdfed6830f3179af65468
      wget https://pypi.python.org/packages/87/74/a4d55da28d7bba6d6f49430f22a62afd8472cb24a63fa61daef80d3e821b/testtools-2.3.0-py2.py3-none-any.whl#md5=eb9ce65ad08afbc7a2bf1b1da9114086
      wget https://pypi.python.org/packages/17/0a/6ac05a3723017a967193456a2efa0aa9ac4b51456891af1e2353bb9de21e/traceback2-1.4.0-py2.py3-none-any.whl#md5=a9b6ac7b5ee15cc7c44b7473135a56d5
      wget https://pypi.python.org/packages/72/20/7f0f433060a962200b7272b8c12ba90ef5b903e218174301d0abfd523813/unittest2-1.1.0-py2.py3-none-any.whl#md5=4fb80726cfd1d8887a75e4a69b9da71a
      ${SAGE} -pip install concurrencytest --no-index --find-links=.
    fi

  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then ${SAGE} -pip install concurrencytest; fi

  - cd ${TRAVIS_BUILD_DIR}

install: ${SAGE} setup.py build_ext --inplace

script: ${SAGE} runtests.py -v -p 10

addons:
  apt:
    packages:
     - gfortran

notifications:
  email: false
