language: python

# note: abelfunctions depends on the git version of sympy due to a related bug
matrix:
  include:
    # Legacy environments (to be implemented)
    # Recommended / Current environments
    - python: "2.7"
      env: DEPS="numpy scipy networkx cython matplotlib"

install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # configuration and installation of test environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION $DEPS
  - source activate test-environment

  # install sympy into the test environment from source
  - git clone https://github.com/sympy/sympy.git
  - cd sympy && python setup.py install && cd ..

  # need to build in-place for tests to run
  - python setup.py build_ext --inplace

script:
  - python setup.py test

