# build matrix consists of different versions of Sage on different platforms.
# the versions are obtained via tarball download since Sage is not a supported
# "language" in TravisCI
#
# choice of Sage version is determined via environment variables
#
env:
  global:
    - SAGE=${HOME}/SageMath/sage

matrix:
  include:
    - os: linux
      env:
        - SAGE_TARBALL=sage-8.0-Ubuntu_14.04-x86_64.tar.bz2
        - SAGE_SERVER=http://mirrors.mit.edu/sage/linux/64bit
      dist: trusty
    - os: osx
      env:
        - SAGE_TARBALL=sage-8.0-OSX_10.12.6-x86_64.tar.bz2
        - SAGE_SERVER=http://mirrors.mit.edu/sage/osx/intel
      osx_image: xcode8.3  # OSX 10.12


before_install:
  # download and extract Sage
  - cd ${HOME}
  - wget ${SAGE_SERVER}/${SAGE_TARBALL}
  - tar xjf ${HOME}/${SAGE_TARBALL}

  # OpenSSL is missing for Sage on OSX but is required to use pip
  # So install concurrencytest and it's dependencies testtools and python-subunit manually
  - |
    if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      wget https://pypi.python.org/packages/e5/d4/9b22df94d0d5c83affe2517295c85fa2d9917f3cafa7dc7f6b1ce4135b00/testtools-2.3.0.tar.gz#md5=0f0feb915497816cb99e39437494217e
      tar xjf ${HOME}/testtools-2.3.0.tar.gz
      cd ${HOME}/testtools-2.3.0.tar.gz
      ${SAGE} -python setup.py install
      cd ${HOME}
      wget https://pypi.python.org/packages/5e/21/7f9bcd20ef93e0f7ef2149e9976f2c6027cab87187f8fedf3c63fd59e2e2/python-subunit-1.2.0.tar.gz#md5=3305455dfe22e2b8666531909c026a2f
      tar xjf ${HOME}/python-subunit-1.2.0.tar.gz
      cd ${HOME}/python-subunit-1.2.0
      ${SAGE} -python setup.py install
      cd ${HOME}
      wget https://pypi.python.org/packages/ba/8a/8286de6d3aa9a3c4765cb3dd73515d91129f012a61e0ec8578c733ea2d27/concurrencytest-0.1.2.tar.gz
      tar xjf ${HOME}/concurrencytest-0.1.2.tar.gz
      cd ${HOME}/concurrencytest-0.1.2
      ${SAGE} -python setup.py install
    fi

  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      ${SAGE} -pip install concurrencytest
    fi

  - cd ${TRAVIS_BUILD_DIR}

install: ${SAGE} setup.py build_ext --inplace

script: ${SAGE} runtests.py -v -p 2

addons:
  apt:
    packages:
     - gfortran

notifications:
  email: false
