# build matrix consists of different versions of Sage on different platforms.
# the versions are obtained via tarball download since Sage is not a supported
# "language" in TravisCI
#
# choice of Sage version is determined via environment variables
#
env:
  global:
    - SAGE=${HOME}/SageMath/sage

matrix:
  include:
    - os: linux
      env:
        - SAGE_TARBALL=sage-8.0-Ubuntu_14.04-x86_64.tar.bz2
        - SAGE_SERVER=http://mirrors.mit.edu/sage/linux/64bit
      dist: trusty
    - os: osx
      env:
        - SAGE_TARBALL=sage-8.0-OSX_10.12.6-x86_64.tar.bz2
        - SAGE_SERVER=http://mirrors.mit.edu/sage/osx/intel
      osx_image: xcode8.3  # OSX 10.12


before_install:
  # download and extract Sage
  - cd ${HOME}
  - wget ${SAGE_SERVER}/${SAGE_TARBALL}
  - travis_wait tar xjf ${HOME}/${SAGE_TARBALL}

  # OpenSSL is missing for Sage on OSX but is required to use pip securely
  - |
    if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      ${SAGE} -pip install --trusted-host pypi.python.org concurrencytest
    fi

  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      ${SAGE} -pip install concurrencytest
    fi

  - cd ${TRAVIS_BUILD_DIR}

install: ${SAGE} setup.py build_ext --inplace

script: ${SAGE} runtests.py -v -p 2

addons:
  apt:
    packages:
     - gfortran

notifications:
  email: false
