sudo: false

# create an spkg from the repo and download the sage binary
before_install:
   - cd ${HOME}/build/abelfunctions
   - tar cjf abelfunctions.spkg abelfunctions
   - mv abelfunctions.spkg ${HOME}
   - cd ${HOME}
   - wget http://mirrors.mit.edu/sage/linux/64bit/sage-7.0-Ubuntu_12.04-x86_64.tar.bz2
   - tar xjf ${HOME}/sage-7.0-Ubuntu_12.04-x86_64.tar.bz2
   - ${HOME}/SageMath/sage -c "print 'Sage Runs!'"
   

install:
  - pwd
  - ${HOME}/SageMath/sage -p ${HOME}/abelfunctions.spkg

script:
  - pwd
  - ${HOME}/SageMath/sage -p -c ${HOME}/abelfunctions.spkg
